---
- import_playbook: ssh_setup.yml

- name: Transfer and execute a script.
  hosts: all
  remote_user: ec2-user
  become: true
  tasks:
     - name: Transfer the script
       copy: src=cloudmapper_script.sh dest=/home/ec2-user mode=0777

     - name: Execute the script
       command: sh /home/ec2-user/cloudmapper_script.sh
